server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:taskdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: false
  cache:
    type: simple

# 開發環境 Eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${random.uuid}

# 開發環境日誌配置
logging:
  level:
    root: INFO
    '[com.example.taskapp]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.data]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

# 開發環境監控配置
management:
  endpoint:
    health:
      show-details: always

# Feign 客戶端配置
feign:
  client:
    config:
      default:
        loggerLevel: full
  circuitbreaker:
    enabled: true
