server:
  port: 8082

spring:
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=taskdb;trustServerCertificate=true;sendTimeAsDateTime=false
    username: simon
    password: 123456
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    # HikariCP 連接池配置
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 300000
      connection-timeout: 20000
      pool-name: TaskHikariPool-dev
      # SQL Server 特定配置
      data-source-properties:
        applicationName: task-service-dev
        lockTimeout: 15000
        queryTimeout: 15
  jpa:
    database-platform: org.hibernate.dialect.SQLServer2012Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        '[format_sql]': true
        '[use_sql_comments]': true
        '[jdbc.batch_size]': 50
        '[jdbc.fetch_size]': 50
        '[order_updates]': true
        '[batch_versioned_data]': true
  cache:
    type: simple

# 開發環境 Eureka 配置
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30
    instance-id: ${spring.application.name}:${random.uuid}

# 開發環境日誌配置
logging:
  level:
    root: INFO
    '[com.example.taskapp]': DEBUG
    '[org.springframework.web]': DEBUG
    '[org.springframework.security]': DEBUG
    '[org.springframework.data]': DEBUG
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE

# 開發環境監控配置
management:
  endpoint:
    health:
      show-details: always

# Feign 客戶端配置
feign:
  client:
    config:
      default:
        loggerLevel: full
  circuitbreaker:
    enabled: true
